#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 21, 2019 04:34:55 PM IST  platform: Windows NT
#    Mar 25, 2019 08:08:09 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global che51
    che51 = tk.StringVar()
    global che52
    che52 = tk.StringVar()
    global che53
    che53 = tk.StringVar()
    global che54
    che54 = tk.StringVar()
    global che55
    che55 = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import studentData
    studentData.vp_start_gui()




