#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  Mar 25, 2019 08:57:59 PM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black -takefocus 1 
    wm focusmodel $top passive
    wm geometry $top 643x696+363+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm iconify $top
    wm title $top "Internal Assessment Record by Kunal & Anish"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#ffffff} -height 255 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 515 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Century} -size 12} -foreground {#000000} \
        -highlightbackground {#ffffff} -highlightcolor black \
        -text {UT 1 Marks} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Century} -size 12} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {UT 2 Marks} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground {#ffffff} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font {-family {Century} -size 13} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Roll Number } 
    vTcl:DefineAlias "$site_3_0.lab47" "Label4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent44 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 10} -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent44" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent45 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 10} -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent45" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 10} -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text AM-IV -variable che51 
    vTcl:DefineAlias "$site_3_0.che51" "maths_checked" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text COA -variable che52 
    vTcl:DefineAlias "$site_3_0.che52" "coa_checked" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che53 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text AOA -variable che53 
    vTcl:DefineAlias "$site_3_0.che53" "aoa_checked" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che54 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text CG -variable che54 
    vTcl:DefineAlias "$site_3_0.che54" "cg_check" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che55 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#ffffff} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text OS -variable che55 
    vTcl:DefineAlias "$site_3_0.che55" "os_checked" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 40 -y 180 -width 94 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 270 -y 180 -width 94 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 130 -y 100 -height 25 -relheight 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent44 \
        -in $site_3_0 -x 260 -y 100 -width 60 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent45 \
        -in $site_3_0 -x 160 -y 180 -width 60 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 390 -y 180 -width 60 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che51 \
        -in $site_3_0 -x 80 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.che52 \
        -in $site_3_0 -x 170 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.che53 \
        -in $site_3_0 -x 250 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.che54 \
        -in $site_3_0 -x 340 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.che55 \
        -in $site_3_0 -x 420 -y 20 -anchor nw -bordermode ignore 
    button $top.but52 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Century} -size 13} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -takefocus 0 -text Submit 
    vTcl:DefineAlias "$top.but52" "Button1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra44 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 285 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 435 
    vTcl:DefineAlias "$top.fra44" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    listbox $site_3_0.lis45 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Arial} -size 12} -foreground {#000000} -height 262 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -selectbackground {#c4c4c4} -selectforeground black -width 414 
    .top42.fra44.lis45 configure -font font16
    .top42.fra44.lis45 insert end text
    vTcl:DefineAlias "$site_3_0.lis45" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lis45 \
        -in $site_3_0 -x 10 -y 10 -width 414 -relwidth 0 -height 262 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but46 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font {-family {Century} -size 13} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Show 
    vTcl:DefineAlias "$top.but46" "Button2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m47
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font {-family {Segoe UI} -size 9} \
        -foreground {#000000} -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 80 -y 20 -width 515 -relwidth 0 -height 255 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 190 -y 320 -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 110 -y 380 -width 435 -relwidth 0 -height 285 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 380 -y 320 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

